### PR TITLE
add PCF857X i2c Digital I/O Expander

### PR DESCRIPTION
**Pull request by cmonicob**
- add pcf8574, pcf8575
- add rtsp cam

### CODE REVIEW

**Comment by theyosh** [comment]
Hi, is this a replacement of the other 2 PRs? Because then I would suggest to use this PR, and close the other 2.

Also, I still think this should be implemented a bit more general. As you could also use this GPIO expander for motion detection or light detection. As those are based on the same button logic as the magnetic door.

Also is it possible to this GPIO expander to read out DHT sensors? That sensor uses a GPIO pin for communication. Do you have an idea about this?

So is it an idea that I merge this PR first, and that we then look how we can make this more generic?

**Comment by cmonicob** [comment]
if it replaces the other 2 PRs.

I have not tried to read DHT sensors, but it could be an interesting implementation

I find a good idea to continue investigating how to get more out of the expander

**Comment by theyosh** [comment]
And I have another question. You have now made 1 door version with a magnetic door sensor. What will happen when you add a second or even third sensor on the expander and use all three as door sensors.
As in my software, I try to check to door (I think) every second. So will that work? Or could that give some strange side affects?

As a more generic solution for buttons (magnetic door, etc) could be by looking at the entered address. Now I have: https://theyosh.github.io/TerrariumPI/hardware/button/magnetic-door-button/#setup
But if you check for `,` in the address, you could split that, and check if the second is a I2C address like `0xab`. If so, then you could assume using a expander. And then make the load device and getting the data aware of that.

Then we need to know what kind of expander it is. For now, we could use again the address field. When the first value had a dash `-` you could create an address like `8-3` or `16-9`. The first part is the 8 or 16 ports version, and the second is the actual used port.

So a full address could then be: `18-9,0x4c,3` which is use port 9 of a 16 ports expander on I2C address 0x4c at bus 3.

If there are more different expander devices, then this could give a problem. But for now, this could work for all buttons like magnetic door, light and motion.

How about that? This is only for buttons now. Relays I am not sure if it is that simple...

**Comment by theyosh** [comment]
So I am tinkering a bit more. A nice example for a sensor is https://theyosh.github.io/TerrariumPI/hardware/sensor/yt-69-sensor-digital/
This is basically a button which is either high or low. Wet or dry. So, this sensor looks like a candidate to be used with an expander. The only thing here is, that this sensor has power management features (https://theyosh.github.io/TerrariumPI/hardware/#power-saving) So an address could then be: `18-9,0x4c,3,25` where the 25 is the power management pin.

This means also, that when you want to use an expander, it is required to enter both I2C address as the I2C bus, even when the bus is default 1.

**Comment by cmonicob** [comment]
I have it working with 3 ports, 1 directly to the raspberry and 2 through the i2c expander.
I have selected sensor type "i2c expander PCF8574" address 0.0x20 where its composition is [expander PIN],[i2c address],[i2c bus]
if you want to optimize the reading of the sensors, the expander sends a string of bits with the status of the pins (10010000) this would mean that pin 0 and 3 are active, it could be programmed that with a single reading of the i2c bus obtain all the states of the gates, it could be seen that if you configure it with [0,3], 0x20 it generates 2 graphics 1 with the state of pin 0 and another with the state of pin 3 of the expander

**Comment by cmonicob** [comment]
> So I am tinkering a bit more. A nice example for a sensor is https://theyosh.github.io/TerrariumPI/hardware/sensor/yt-69-sensor-digital/ This is basically a button which is either high or low. Wet or dry. So, this sensor looks like a candidate to be used with an expander. The only thing here is, that this sensor has power management features (https://theyosh.github.io/TerrariumPI/hardware/#power-saving) So an address could then be: `18-9,0x4c,3,25` where the 25 is the power management pin.
> 
> This means also, that when you want to use an expander, it is required to enter both I2C address as the I2C bus, even when the bus is default 1.

there would be no problem in associating a pin to have a sleep mode

**Comment by theyosh** [comment]
Hi, I was still checking some code and I get the feeling that the following line is not correct, but does work ;)
`self._device['in_port'] = int(address[0]) if self._PIN_OUT == None else self._PIN_OUT[int(address[0])]`
https://github.com/theyosh/TerrariumPI/pull/665/files#diff-16bf01bae203b3d83c725fac90c4e65dd4a5117ab23267eff30d5af10bf9de04R29

Because checking on `== None` is not correct. That should be `is None` as far I know. Therefore the second part is always executed. But then I think it is strange that you invert the number when the PIN_OUT is available. Because the relay is backwards in numbering.

So that should mean that when there is no PIN_OUT, the number should be `MAX_VALUE - ENTERED_VALUE`

But, I guess that using the PIN_OUT array works, and that that is the correct code.

And based on this all, I have created the following code. Totally untested, but this is the more generic way I was looking for:
A general IO Expander: https://github.com/theyosh/TerrariumPI/blob/IOexpander/hardware/io_expander.py
Using it in the buttons: https://github.com/theyosh/TerrariumPI/blob/IOexpander/hardware/button/__init__.py#L123 and https://github.com/theyosh/TerrariumPI/blob/IOexpander/hardware/button/__init__.py#L113

This way, there is no need to create new hardware items. You can now select the 'normal' magnetic door sensor and enter an address like: `16-9,0x4c,1` to specify a 16 port IO expander (PCF8575) on port 9 with I2C addres 0x4c on bus 1.

Also this should also work for a motion detector. But not for LDR, because that needs than also a IO expander code/logic.

And for relays, we can use the same IO Expander code. So less duplicating code and easier to maintain.

How about this way? It does mean changing you code, or test my changes. As I do not have the hardware.

**Comment by cmonicob** [comment]
I think this implementation is much more elegant because we can reuse the code in all its parts,

After carrying out the tests to incorporate this implementation in the creation of the magnetic button, the error appears:
Button could not be added: object.__new__(X): X is not a type object (function)

**Comment by theyosh** [comment]
Ah, I found some more code issues. But I think the IOexpander branch should now work. I get errors about missing hardware, but that is to be expected. I do not own this kind of hardware.

But I am still not sure about your code with the _PIN_OUT array. So I removed that and used the function call `get_pin_state` which just takes the actual pin number. But again, I cannot test this.

So if you could test the new branch, and see if that works with your hardware, I think we are close of refactoring the relays as well.

**Comment by theyosh** [comment]
Oh, and I did change the address input to 'PCF8574-3,0x4c,1' so we can support more IO expander boards.

**Comment by cmonicob** [comment]
now everything is correct,

the remapping of the pinout is because the hardware I use is inverted to that of the library, I don't know if it is a defect of the library or of the PCB manufacturer but I have found the error in both pcf8574 and pcf8575

**Comment by cmonicob** [comment]
now everything is correct,

the remapping of the pinout is because the hardware I use is inverted to that of the library, I don't know if it is a defect of the library or of the PCB manufacturer but I have found the error in both pcf8574 and pcf8575

**Comment by theyosh** [comment]
Ok, I have also added the same logic for GPIO (inverse) relays. So you can now also use the same address formatting for relays.

If you can test this, and see if the relay will toggle using the IO expander. Then we are getting close to a more generic solution for IO expanders

**Comment by theyosh** [comment]
Have you been able to test the IO expander, my code and a relay? That should also work now. Then I think the IO expander is implemented.

About the RTSP camera, are you sure it works? Looks strange the use OpenCV to read a remote source... https://github.com/theyosh/TerrariumPI/pull/665/files#diff-cf6c479a4b3dc72aa4f99fe6fce65586bbce87a8777c2144e18c694e1b489829

**Comment by cmonicob** [comment]
I've been testing the code and I can't add any relay, I don't know why but I get an error from the PWM GPIO module (Relay could not be added. Unknown attribute 'dimmer_max_dim')

Regarding rtsp I have a video surveillance camera in the terrarium and it works correctly to capture frames and view them, I hope in the future to modify the code so that the video stream is realtime

**Comment by theyosh** [comment]
Hmm, found the relay adding issue. Should be fixed by doing a `git pull` and refresh your browser. If the error is still there, make sure your have cleaned your browser cache

**Comment by theyosh** [comment]
Did you have time to test the new IO expander code? If you do a `git pull` now, you **need** to rerun the installer. I have merged with the 4.x.y.z branch, which has some new sensors.

I also added the RTSP camera, but with different code. As it is based on the USB code, I have reused that code. Are you able to test this as well? If it is working, we have implemented this PR, but then more generic and with a bit better code.

**Comment by cmonicob** [comment]
in one of the updates I crashed the system and had to reinstall from scratch,
I hope this week to have all the tests finished

**Comment by cmonicob** [comment]
at the moment all the tests of hardware operation are correct.

I don't know if it could be because of the new code but the refresh of the actions is somewhat slow, and sometimes it is necessary to reload the page

**Comment by cmonicob** [comment]
After performing all the tests and adapting the reverse GPIO everything works fine, they can implement IOExpander GPIO as if it were native to the raspberry.
After clearing the cache and restarting the DB the response time of the GUI and actuators is normal.
The rtmp video surveillance camera also works properly.

**Comment by theyosh** [comment]
Nice!. I have merged the GPIO inverse fix. So then everything is done, and this PR will then just closed. Also the IOexpander branch will be merged in the main branch with the next release, which I hope to make this or next week.

The slowness of the relay toggling is something that I noticed also. It has to do with the database usage. I am looking to see if I can improve that a bit more...

Thanks for adding code and testing it!

**Pull request closed without merging**
