### PR TITLE
Add EC (Electrical conductivity) expressed in mS (microSiemens) 

### PR DESCRIPTION
**Pull request by nke69**
Hello,

As for pH, I just added the values for the electrical conductivity (EC) expressed in microSiemens (mS).
This is very useful for aquarists, it's up to you to see if you want to integrate it into the software;)

Have a good day

### CODE REVIEW

**Comment by nke69** [comment]
For infos I made my probe by following this tutorial:
http://flowrc.co.uk/conductivity_probe.html

This one is connected to my arduino;)

**Comment by theyosh** [comment]
Cool, but I am wondering how you read the sensor. Because I only see that the type is allowed, but I never see where it will be read out. Or is this done through a remote option?

**Comment by nke69** [comment]
yes the script is on the arduino, I get the values in remote actually;)

**Comment by nke69** [comment]
Hello,

here is the assembly that I use with arduino for the calculation of the electrical conductivity. I finally followed this plan because the previous one was causing electrolysis :(
This is not normally the case now.

link to the tutorial (script and DIY diagram of the probe), go to chapter 5:

https://alejandroquinteros.files.wordpress.com/2012/11/environmental-monitoring-with-arduino.pdf

arduino skecth:

/*
  Water Conductivity Monitor
  Sketch for an Arduino gadget that measures the electrical
  conductivity of water.
  This example code is based on example code that is in the public domain.
*/
const float ArduinoVoltage = 5.00; // CHANGE THIS FOR 3.3v Arduinos
const float ArduinoResolution = ArduinoVoltage / 1024;
const float resistorValue = 10000.0;
int threshold = 3;
int inputPin = A0;
int ouputPin = A5;
void setup()
{
  Serial.begin(9600);
  pinMode(ouputPin, OUTPUT);
  pinMode(inputPin, INPUT);
}
void loop()
{
  int analogValue = 0;
  int oldAnalogValue = 1000;
  float returnVoltage = 0.0;
  float resistance = 0.0;
  double Siemens;
  float TDS = 0.0;
  while (((oldAnalogValue - analogValue) > threshold) || (oldAnalogValue < 50))
  {
    oldAnalogValue = analogValue;
    digitalWrite( ouputPin, HIGH );
    delay(10); // allow ringing to stop
    analogValue = analogRead( inputPin );
    digitalWrite( ouputPin, LOW );
  }
  Serial.print("Return voltage = ");
  returnVoltage = analogValue * ArduinoResolution;
  Serial.print(returnVoltage);
  Serial.println(" volts");
  Serial.print("That works out to a resistance of ");
  resistance = ((5.00 * resistorValue) / returnVoltage) - resistorValue;
  Serial.print(resistance);
  Serial.println(" Ohms.");
  Serial.print("Which works out to a conductivity of ");
  Siemens = 1.0 / (resistance / 1000000);
  Serial.print(Siemens);
  Serial.println(" microSiemens.");
  Serial.print("Total Dissolved Solids are on the order of ");
  TDS = 500 * (Siemens / 1000);
  Serial.print(TDS);
  Serial.println(" PPM.");
  if (returnVoltage > 4.9) Serial.println("Are you sure this isn't metal?");
  delay(5000);
}

**Comment by theyosh** [comment]
Cool. very nice! Thanks a lot

**Pull request merged**
