### PR TITLE
Support for Honeywell HumidIcon sensors

### PR DESCRIPTION
**Pull request by mikenorgate**
This adds support for Honeywell HumidIcon HIH8000 Series temperature and humidity sensors

### CODE REVIEW

**Comment by theyosh** [comment]
Hi, cool and thanks!

I did see some print output which I think is not needed: https://github.com/theyosh/TerrariumPI/pull/549/files#diff-0d472d24e435ca51834094f3e2546865e2a8781f87f9a497119d37a469a605e3R656

Then I will merge it. And make it also working for TP4.

**Comment by mikenorgate** [comment]
@theyosh I've cleaned up my debug logs

**Comment by theyosh** [comment]
Thanks, got it merged with the master. And I will make a TP4 version. Is it possible for you to do some testing next week? #539

**Comment by theyosh** [comment]
Hi, I have added this sensor also in TP4. Are you able to test this? #539

**Comment by mikenorgate** [comment]
I'll try and give it a go over the weekend

**Comment by mikenorgate** [comment]
Just tried to run TP4 but get the following error which is stopping it from starting

```
May 15 11:07:24 terrarium systemd[1]: Starting TerrariumPI...
May 15 11:07:55 terrarium systemd[1]: Started TerrariumPI.
May 15 11:07:55 terrarium python[882]: 2021-05-15 11:07:55,688 - INFO    - terrariumEngine      - Starting TerrariumPI 4.0.0 ...
May 15 11:07:56 terrarium python[882]: 2021-05-15 11:07:56,047 - INFO    - terrariumEngine      - Loaded 27 settings in 0.33 seconds.
May 15 11:08:01 terrarium python[882]: 2021-05-15 11:08:01,509 - INFO    - terrariumEngine      - Loading existing sensors from database.
May 15 11:08:01 terrarium python[882]: 2021-05-15 11:08:01,554 - INFO    - terrariumEngine      - Scanning for new sensors ...
May 15 11:08:04 terrarium python[882]: 2021-05-15 11:08:04,863 - WARNING - __init__             - Bluetooth scanning is not enabled for normal users or there are zero Bluetooth LE devices available.... bluetooth is disabled!
May 15 11:08:06 terrarium python[882]: 2021-05-15 11:08:06,193 - WARNING - __init__             - Bluetooth scanning is not enabled for normal users or there are zero Bluetooth LE devices available.... bluetooth is disabled!
May 15 11:08:06 terrarium python[882]: 2021-05-15 11:08:06,338 - INFO    - terrariumEngine      - Loaded 0 sensors in 4.83 seconds.
May 15 11:08:06 terrarium python[882]: 2021-05-15 11:08:06,344 - INFO    - terrariumEngine      - Loading existing relays from database.
May 15 11:08:06 terrarium python[882]: 2021-05-15 11:08:06,381 - INFO    - terrariumEngine      - Scanning for new relays ...
May 15 11:08:08 terrarium python[882]: No GEMBIRD SiS-PM found. Check USB connections, please!
May 15 11:08:08 terrarium python[882]: Traceback (most recent call last):
May 15 11:08:08 terrarium python[882]:   File "/TerrariumPI/terrariumPI.py", line 19, in <module>
May 15 11:08:08 terrarium python[882]:     terrariumEngine = terrariumEngine(__version__)
May 15 11:08:08 terrarium python[882]:   File "/TerrariumPI/terrariumEngine.py", line 131, in __init__
May 15 11:08:08 terrarium python[882]:     self.scan_new_relays()
May 15 11:08:08 terrarium python[882]:   File "/TerrariumPI/terrariumEngine.py", line 651, in scan_new_relays
May 15 11:08:08 terrarium python[882]:     for relay in terrariumRelay.scan_relays(callback=self.callback_relay):
May 15 11:08:08 terrarium python[882]:   File "/TerrariumPI/hardware/relay/__init__.py", line 286, in scan_relays
May 15 11:08:08 terrarium python[882]:     for relay in relay_device._scan_relays(callback, **kwargs):
May 15 11:08:08 terrarium python[882]:   File "/TerrariumPI/hardware/relay/kasa_relay.py", line 123, in _scan_relays
May 15 11:08:08 terrarium python[882]:     found_devices = data.result()
May 15 11:08:08 terrarium python[882]:   File "/usr/lib/python3.7/concurrent/futures/_base.py", line 427, in result
May 15 11:08:08 terrarium python[882]:     self._condition.wait(timeout)
May 15 11:08:08 terrarium python[882]:   File "/usr/lib/python3.7/threading.py", line 296, in wait
May 15 11:08:08 terrarium python[882]:     waiter.acquire()
May 15 11:08:08 terrarium python[882]:   File "/TerrariumPI/venv/lib/python3.7/site-packages/gevent/thread.py", line 121, in acquire
May 15 11:08:08 terrarium python[882]:     acquired = BoundedSemaphore.acquire(self, blocking, timeout)
May 15 11:08:08 terrarium python[882]:   File "src/gevent/_semaphore.py", line 180, in gevent._gevent_c_semaphore.Semaphore.acquire
May 15 11:08:08 terrarium python[882]:   File "src/gevent/_semaphore.py", line 259, in gevent._gevent_c_semaphore.Semaphore.acquire
May 15 11:08:08 terrarium python[882]:   File "src/gevent/_semaphore.py", line 249, in gevent._gevent_c_semaphore.Semaphore.acquire
May 15 11:08:08 terrarium python[882]:   File "src/gevent/_abstract_linkable.py", line 521, in gevent._gevent_c_abstract_linkable.AbstractLinkable._wait
May 15 11:08:08 terrarium python[882]:   File "src/gevent/_abstract_linkable.py", line 487, in gevent._gevent_c_abstract_linkable.AbstractLinkable._wait_core
May 15 11:08:08 terrarium python[882]:   File "src/gevent/_abstract_linkable.py", line 490, in gevent._gevent_c_abstract_linkable.AbstractLinkable._wait_core
May 15 11:08:08 terrarium python[882]:   File "src/gevent/_abstract_linkable.py", line 442, in gevent._gevent_c_abstract_linkable.AbstractLinkable._AbstractLinkable__wait_to_be_notified
May 15 11:08:08 terrarium python[882]:   File "src/gevent/_abstract_linkable.py", line 451, in gevent._gevent_c_abstract_linkable.AbstractLinkable._switch_to_hub
May 15 11:08:08 terrarium python[882]:   File "src/gevent/_greenlet_primitives.py", line 61, in gevent._gevent_c_greenlet_primitives.SwitchOutGreenletWithLoop.switch
May 15 11:08:08 terrarium python[882]:   File "src/gevent/_greenlet_primitives.py", line 65, in gevent._gevent_c_greenlet_primitives.SwitchOutGreenletWithLoop.switch
May 15 11:08:08 terrarium python[882]:   File "src/gevent/_gevent_c_greenlet_primitives.pxd", line 35, in gevent._gevent_c_greenlet_primitives._greenlet_switch
May 15 11:08:08 terrarium python[882]: gevent.exceptions.LoopExit: This operation would block forever
May 15 11:08:08 terrarium python[882]:         Hub: <Hub '' at 0xb57d7b28 epoll default pending=0 ref=0 fileno=4 resolver=<gevent.resolver.thread.Resolver at 0xab47a370 pool=<ThreadPool at 0xb50d5500 tasks=0 size=1 maxsize=10 hub=<Hub a
May 15 11:08:08 terrarium python[882]:         Handles:
May 15 11:08:08 terrarium python[882]: []
May 15 11:08:10 terrarium systemd[1]: terrariumpi.service: Main process exited, code=exited, status=1/FAILURE
May 15 11:08:10 terrarium systemd[1]: terrariumpi.service: Failed with result 'exit-code'.
```

**Comment by theyosh** [comment]
Hmm, I got almost the same error when I do not have a Meross account. So I updated the code to fix the above. 

Could you do a `git pull` and then restart: `sudo service terrariumpi start`? I hope that it will start now.

**Comment by mikenorgate** [comment]
@theyosh That has solved then start up issue, but I have found a problem with the sensors.

Adding the temperature and humidity sensors individually is fine and they show the correct values, but having both of them together causes an error

Single sensor 

image

Both sensors

image


Also I'm not able to create an enclosure. I just get "Enclosure could not be added" error

**Comment by theyosh** [comment]
Hmm, I fixed the enclosure adding bug. That should be fixed now. Do a `git pull` and restart terrariumPI.

About the sensors, could it be that id needed some more time to give the right values? Because I can't think why this is happening.

Is there any error message in the log/terrariumpi.log ? Or there could be some messages in /var/log/syslog

**Comment by mikenorgate** [comment]
@theyosh I added a bit of logging to see check when the sensor was being read and think I've identified the problem

As you can see from the log below the sensor update loop doesn't seem to start after adding the sensors, after restarting the service the update loop starts and everything is fine.

I'm guessing the `__engine_loop` is erroring if there are somewhere if there are no sensors and stopping

```
2021-05-16 09:33:05,646 - INFO    - terrariumEngine      - Starting TerrariumPI 4.0.0 ...
2021-05-16 09:33:06,072 - INFO    - terrariumEngine      - Loaded 27 settings in 0.35 seconds.
2021-05-16 09:33:12,061 - INFO    - terrariumEngine      - Loading existing sensors from database.
2021-05-16 09:33:12,108 - INFO    - terrariumEngine      - Scanning for new sensors ...
2021-05-16 09:33:14,376 - WARNING - __init__             - Bluetooth scanning is not enabled for normal users or there are zero Bluetooth LE devices available.... bluetooth is disabled!
2021-05-16 09:33:15,706 - WARNING - __init__             - Bluetooth scanning is not enabled for normal users or there are zero Bluetooth LE devices available.... bluetooth is disabled!
2021-05-16 09:33:15,911 - INFO    - terrariumEngine      - Loaded 0 sensors in 3.85 seconds.
2021-05-16 09:33:15,917 - INFO    - terrariumEngine      - Loading existing relays from database.
2021-05-16 09:33:15,972 - INFO    - terrariumEngine      - Scanning for new relays ...
2021-05-16 09:33:34,236 - INFO    - terrariumEngine      - Loaded 0 relays in 18.32 seconds.
2021-05-16 09:33:34,251 - INFO    - terrariumEngine      - Loading existing buttons from database.
2021-05-16 09:33:34,312 - INFO    - terrariumEngine      - Loaded 0 buttons in 0.06 seconds.
2021-05-16 09:33:34,318 - INFO    - terrariumEngine      - Loading existing webcams from database.
2021-05-16 09:33:34,353 - INFO    - terrariumEngine      - Loaded 0 webcams in 0.04 seconds.
2021-05-16 09:33:34,359 - INFO    - terrariumEngine      - Loading existing enclosures from database.
2021-05-16 09:33:34,391 - INFO    - terrariumEngine      - Loaded 0 enclosures in 0.03 seconds.
2021-05-16 09:33:34,397 - INFO    - terrariumEngine      - TerrariumPI is up and running at address: http://0.0.0.0:8090 in 31.76 seconds.
2021-05-16 09:33:34,406 - INFO    - terrariumEngine      - Starting log tailing.
2021-05-16 09:33:34,469 - INFO    - terrariumEngine      - Starting engine updater with 30.00 seconds interval.
2021-05-16 09:33:34,485 - INFO    - terrariumWebserver   - Running webserver at 0.0.0.0:8090
2021-05-16 09:33:34,734 - INFO    - terrariumEngine      - Starting a new update round with 0 sensors, 0 relays, 0 buttons and 0 webcams.
2021-05-16 09:36:05,216 - ERROR   - hih8000_sensor       - HIH data {'humidity': 88.26761079233304, 'temperature': 20.109876693932364}    <----- ADDED SENSOR
2021-05-16 09:43:10,259 - ERROR   - hih8000_sensor       - HIH data {'humidity': 90.41631058478818, 'temperature': 19.737211573678422}    <----- ADDED SENSOR
------ NO UPDATES TO SENSOR INFORMATION ------
2021-05-16 09:46:29,106 - INFO    - terrariumEngine      - Stopping TerrariumPI 4.0.0 ...
2021-05-16 09:46:29,144 - INFO    - terrariumEngine      - Stopped log tailing.
2021-05-16 09:46:29,167 - INFO    - terrariumEngine      - Stopped Enclosure Default with 0 areas
2021-05-16 09:46:29,180 - INFO    - terrariumEngine      - Stopped Honeywell HumidIcon HIH8000 humidity named 'Humidity' at address '27,1'
2021-05-16 09:46:29,189 - INFO    - terrariumEngine      - Stopped Honeywell HumidIcon HIH8000 temperature named 'Temperature' at address '27,1'
2021-05-16 09:46:29,199 - INFO    - terrariumPI          - Shutdown TerrariumPI 4.0.0 done. Bye bye ...
2021-05-16 09:47:03,246 - INFO    - terrariumEngine      - Starting TerrariumPI 4.0.0 ...
2021-05-16 09:47:03,667 - INFO    - terrariumEngine      - Loaded 27 settings in 0.35 seconds.
2021-05-16 09:47:09,104 - INFO    - terrariumEngine      - Loading existing sensors from database.
2021-05-16 09:47:09,220 - ERROR   - hih8000_sensor       - HIH data {'humidity': 91.02673666219022, 'temperature': 19.555915028690023}
2021-05-16 09:47:09,342 - INFO    - terrariumEngine      - Loaded sensor hih8000 humidity named 'Humidity' at address '27,1' with value 91.03% in 0.19 seconds.
2021-05-16 09:47:09,369 - INFO    - terrariumEngine      - Loaded sensor hih8000 temperature named 'Temperature' at address '27,1' with value 19.56C in 0.02 seconds.
2021-05-16 09:47:09,381 - INFO    - terrariumEngine      - Scanning for new sensors ...
2021-05-16 09:47:11,775 - WARNING - __init__             - Bluetooth scanning is not enabled for normal users or there are zero Bluetooth LE devices available.... bluetooth is disabled!
2021-05-16 09:47:13,276 - WARNING - __init__             - Bluetooth scanning is not enabled for normal users or there are zero Bluetooth LE devices available.... bluetooth is disabled!
2021-05-16 09:47:13,501 - INFO    - terrariumEngine      - Loaded 2 sensors in 4.40 seconds.
2021-05-16 09:47:13,507 - INFO    - terrariumEngine      - Loading existing relays from database.
2021-05-16 09:47:13,562 - INFO    - terrariumEngine      - Scanning for new relays ...
2021-05-16 09:47:31,370 - INFO    - terrariumEngine      - Loaded 0 relays in 17.86 seconds.
2021-05-16 09:47:31,385 - INFO    - terrariumEngine      - Loading existing buttons from database.
2021-05-16 09:47:31,438 - INFO    - terrariumEngine      - Loaded 0 buttons in 0.05 seconds.
2021-05-16 09:47:31,445 - INFO    - terrariumEngine      - Loading existing webcams from database.
2021-05-16 09:47:31,512 - INFO    - terrariumEngine      - Loaded 0 webcams in 0.06 seconds.
2021-05-16 09:47:31,524 - INFO    - terrariumEngine      - Loading existing enclosures from database.
2021-05-16 09:47:31,637 - INFO    - terrariumEngine      - Loaded Enclosure Default with 0 areas in 0.04 seconds.
2021-05-16 09:47:31,649 - INFO    - terrariumEngine      - Loaded 1 enclosures in 0.13 seconds.
2021-05-16 09:47:31,660 - INFO    - terrariumEngine      - TerrariumPI is up and running at address: http://0.0.0.0:8090 in 31.33 seconds.
2021-05-16 09:47:31,676 - INFO    - terrariumEngine      - Starting log tailing.
2021-05-16 09:47:31,835 - INFO    - terrariumEngine      - Starting engine updater with 30.00 seconds interval.
2021-05-16 09:47:31,851 - INFO    - terrariumWebserver   - Running webserver at 0.0.0.0:8090
2021-05-16 09:47:32,099 - INFO    - terrariumEngine      - Starting a new update round with 2 sensors, 0 relays, 0 buttons and 0 webcams.
2021-05-16 09:47:32,366 - INFO    - terrariumEngine      - Updated sensor hih8000 humidity named 'Humidity' at address '27,1' with new value 91.03% in 0.02 seconds.
2021-05-16 09:47:32,407 - INFO    - terrariumEngine      - Updated sensor hih8000 temperature named 'Temperature' at address '27,1' with new value 19.56C in 0.01 seconds.
2021-05-16 09:47:33,291 - INFO    - terrariumEngine      - Updated Enclosure Default with 0 areas in 0.02 seconds.
2021-05-16 09:47:33,683 - INFO    - terrariumEngine      - Engine update done in 1.58 seconds. Waiting for 28.42 seconds for the next round.
2021-05-16 09:48:02,108 - INFO    - terrariumEngine      - Starting a new update round with 2 sensors, 0 relays, 0 buttons and 0 webcams. <----- SENSORS UPDATING AS EXPECTED
2021-05-16 09:48:02,288 - ERROR   - hih8000_sensor       - HIH data {'humidity': 91.07557074838238, 'temperature': 19.545842998412887}
2021-05-16 09:48:02,360 - INFO    - terrariumEngine      - Updated sensor hih8000 humidity named 'Humidity' at address '27,1' with new value 91.08% in 0.20 seconds.
2021-05-16 09:48:02,404 - INFO    - terrariumEngine      - Updated sensor hih8000 temperature named 'Temperature' at address '27,1' with new value 19.55C in 0.02 seconds.
2021-05-16 09:48:02,514 - INFO    - terrariumEngine      - Updated Enclosure Default with 0 areas in 0.02 seconds.
2021-05-16 09:48:02,864 - INFO    - terrariumEngine      - Engine update done in 0.75 seconds. Waiting for 29.25 seconds for the next round.
2021-05-16 09:48:32,116 - INFO    - terrariumEngine      - Starting a new update round with 2 sensors, 0 relays, 0 buttons and 0 webcams.
2021-05-16 09:48:32,367 - ERROR   - hih8000_sensor       - HIH data {'humidity': 91.14882187767061, 'temperature': 19.505554877304355}
2021-05-16 09:48:32,442 - INFO    - terrariumEngine      - Updated sensor hih8000 humidity named 'Humidity' at address '27,1' with new value 91.15% in 0.25 seconds.
2021-05-16 09:48:32,502 - INFO    - terrariumEngine      - Updated sensor hih8000 temperature named 'Temperature' at address '27,1' with new value 19.51C in 0.03 seconds.
2021-05-16 09:48:32,646 - INFO    - terrariumEngine      - Updated Enclosure Default with 0 areas in 0.02 seconds.
2021-05-16 09:48:33,142 - INFO    - terrariumEngine      - Engine update done in 1.02 seconds. Waiting for 28.98 seconds for the next round.
```

**Comment by theyosh** [comment]
Ah, I thought I had fixed that. But apparently not. So I made another update and it should work now. Could you do a `git pull` and restart?

But it looks like the Honeywell sensors are working....

**Comment by mikenorgate** [comment]
All looks good. 

Yes I can confirm the Honeywell sensors are working correctly

**Comment by theyosh** [comment]
Cool! Then for now, I know enough. If you want to do some testing... and find issues, please report them in #539 

And thanks for submitting the code...

**Pull request merged**
